

services:
  postgres:
    image: postgres:16
    container_name: ${POSTGRES_CONTAINER}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./posey_data:/docker-entrypoint-initdb.d:ro
    restart: unless-stopped

  adminer:
    image: adminer
    container_name: ${ADMINER_CONTAINER}
    ports:
      - "${ADMINER_PORT}:8080"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  pg_data:
